"""Tests for automatic documentation generation."""

from __future__ import annotations

import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
SCRIPT = REPO_ROOT / "scripts" / "update_docs.py"


def test_update_docs_generates_files(tmp_path: Path) -> None:
    docs_dir = tmp_path / "docs"
    docs_dir.mkdir()

    env = {"PYTHONPATH": str(REPO_ROOT / "src")}
    result = subprocess.run(
        [sys.executable, str(SCRIPT)],
        cwd=REPO_ROOT,
        check=False,
        capture_output=True,
        text=True,
        env={**dict(**__import__("os").environ), **env},
    )
    assert result.returncode == 0, result.stderr

    for name in ("api.md", "cli.md", "schemas.md"):
        path = REPO_ROOT / "docs" / name
        assert path.is_file()
        content = path.read_text(encoding="utf-8")
        assert "Generated by scripts/update_docs.py" in content
        assert len(content) > 200


def test_discover_cli_and_models() -> None:
    import importlib.util

    spec = importlib.util.spec_from_file_location("update_docs", SCRIPT)
    assert spec and spec.loader
    module = importlib.util.module_from_spec(spec)
    sys.modules["update_docs"] = module
    spec.loader.exec_module(module)

    commands = module.discover_cli_commands()
    models = module.discover_pydantic_models()

    assert any(command.name == "validate-fsm" for command in commands)
    assert any(command.name == "benchmark-evolution compare" for command in commands)
    assert any(model.name == "FSM" for model in models)
    assert any(model.name == "BugMetadata" for model in models)


def test_generated_cli_contains_usage_examples() -> None:
    cli_doc = (REPO_ROOT / "docs" / "cli.md").read_text(encoding="utf-8")
    assert "fsmrepairbench validate-fsm tests/fixtures/valid_fsm.json" in cli_doc
    assert "### `build-dataset`" in cli_doc


def test_generated_api_contains_models() -> None:
    api_doc = (REPO_ROOT / "docs" / "api.md").read_text(encoding="utf-8")
    assert "### `FSM`" in api_doc
    assert "`initial_state`" in api_doc


def test_generated_schemas_contains_versions() -> None:
    schemas_doc = (REPO_ROOT / "docs" / "schemas.md").read_text(encoding="utf-8")
    assert "`v2.0`" in schemas_doc
    assert "case_metadata.json" in schemas_doc
